config/routes.rb
Workflow::Application.routes.draw do
  resources :parameters

  resources :users

  resources :applications

  match 'all_applications(.:format)' => 'applications#index_all', :as => "index_all"
  match 'login(.:format)' => 'login#index', :as => "login", :via => "get"
  match 'login(.:format)' => 'login#auth', :as => "login", :via => "post"
  match 'logout(.:format)' => 'login#logout', :as => "logout", :via => "get"

  root :to => 'login#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :body, :end, :start, :to, :user_id, :status, :apply_date
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :logged_in?

  def logged_in?
    if session[:user].blank?
        return if params[:controller] == "login"
        redirect_to :controller => "login" , :action => "index"
    else
        @login_user = session['user']
        @login_user_role = session['user_role']
    end
  end
end

app/controllers/applications_controller.rb
require "aws-sdk"
require 'job'

class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json

  def get_all_instances
    @access_key = Parameter.find(:first,:conditions => {:key => "aws_access_key"})
    @secret_key = Parameter.find(:first,:conditions => {:key => "aws_secret_access_key"})
    @region = "ec2.ap-northeast-1.amazonaws.com"

    AWS.config(:access_key_id => access_key['value'],:secret_access_key => secret_key['value'],:ec2_endpoint => region)

    h = Hash.new
    begin
        ec2 = AWS::EC2.new()
        instances = ec2.instances()
        instances.each { | instance |
          name = instance.tags['Name']
          h[name] = "#{name}(#{instance.id})"
        }
        p h
    rescue  => e
        puts e
    end   
  end

  
  def index
    @applications = Application.find(:all,:conditions => ["status = ? or status = ? ",0,2] ,:order => "apply_date desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

    def index_all
    @applications = Application.find(:all,:order => "apply_date desc")

    respond_to do |format|
      format.html {render "index"}
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    #表示は誰でもできる
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new

    #申請は誰でもできる
    @application = Application.new
    user = User.find_by_user(@login_user)
    puts user

    @application['user_id'] = user.id
    @application['user'] = user

    @instances = get_all_instances

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])
    p @params
    user = User.find_by_user(params['requester'])
    puts user

    @application['user_id'] = user.id
    @application['status'] = 0
    @application['apply_date'] = Time.now


    @application['to'] = params[:application]['to'].join(",")

    respond_to do |format|
      if @application.save
        format.html { redirect_to :action => "index", notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update

    unless @login_user_role == "1"
      flash[:error] =  "You don't have paermission."
      redirect_to :action => "index"
      return
      p "hoge"
    end

    #approveおよびdenyは承認者権限のみなのでチェックが必要
    @application = Application.find(params[:id])
    result = false
    if params['commit'] == "approve"
      result = @application.update_attribute("status",1)





      #ary = ParseDate::parsedate(@application['start']) #=> [2001, 5, 24, 22, 56, 30, "JST", 4]
      #t = Time::local(*ary[0..-3]) #=> Thu May 24 22:56:30 JST 2001

#2013-06-13 20:56:11 UTC

      starttime = Time.strptime(@application['start'].to_s, '%Y-%m-%d %H:%M:%S')
      endtime = Time.strptime(@application['start'].to_s, '%Y-%m-%d %H:%M:%S')

      job = Job.new

      #sgの算出処理必要
      #job.send_at starttime, :authorize_ingress_from_gw_to_target, @access_key, @secret_access_key, @region,sg
      #job.send_at endtime, :revoke_ingress_from_gw_to_target, @access_key, @secret_access_key, @region,sg


    elsif params['commit'] == "deny"
      result = @application.update_attribute("status",2)
    end
    respond_to do |format|
      if result
        format.html { redirect_to :action => "index", notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label><%= @login_user %></label>
    <input type="hidden" name="requester" value="<%= @login_user %>"></input>
  </div>
  <div>
    <%= f.label :start %>
  <div id="datetimepicker1" class="input-append date">
    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="application[start]"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>

  </div>
  <div>
    <%= f.label :end %>
  <div id="datetimepicker2" class="input-append date">
    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="application[end]"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>
  </div>
  <div>
    <%= f.label :to %>
    <%= select_tag "application[to]", options_for_select(@instances),{:multiple => true}%>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, :size => "50x5"%>
  </div>
  <div class="actions">
    <%= f.submit :apply,:class=>"btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<% if flash[:error] %>
    <div class="alert alert-error"><%= flash[:error] %></div>
<% end %>
<h1>Listing applications</h1>
<div class= "index_list_all"><%= link_to "show all", :controller => "applications", :action => "index_all" %></div>
<table class="table table-hover">
  <tr>
    <th>Date of application</th>
    <th>User</th>
    <th>Start</th>
    <th>End</th>
    <th>To</th>
    <th>Body</th>
    <th>Status</th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.apply_date %></td>
    <td><%= application.user['user'] %></td>
    <td><%= application.start %></td>
    <td><%= application.end %></td>
    <td><%= application.to %></td>
    <td><%= application.body %></td>
    <td>
        <%=
            status = "申請中"
            case application.status
            when 1
                status = "承認済"
            when 2
                status = "否決"
            else
                status = "申請中"
            end
         %></td>
    <td><%= link_to 'Show', application %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, @application.user['user'] %>
  </div>
  <div>
    <%= f.label :start %>
    <input type="text" value="<%= @application.start %>"></input>
  </div>
  <div>
    <%= f.label :end %>
    <input type="text" value="<%= @application.end %>"></input>
  </div>
  <div>
    <%= f.label :to %>
    <%= f.text_field :to %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <input type="hidden" name="application[id]" value="<%= @application.id %>"></input> 
    <%= f.submit :approve,:class=>"btn btn-large btn-primary" %>
    <%= f.submit :deny,:class=>"btn btn-large " %>
  </div>
<% end %>
<%= link_to 'Back', applications_path %>